options {
    directory "/var/cache/bind";
    allow-recursion { any; };
    allow-query { any; };

    dnssec-validation auto;
    listen-on-v6 { any; };
};

zone "localhost" IN {
    type master;
    file "/etc/bind/zones/db.localhost";
};

zone "cloud.local" IN {
    type master;
    file "/etc/bind/zones/db.cloud.local";
};